spring:
  application:
    name: RokuganBackend
  profiles:
    active: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rokugan_db
      username: rokugan_app
      password: rokugan
